name: Deploy Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x 

      # Build backend
      - name: Build backend
        run: |
          cd backend
          dotnet publish -c Release -o ./publish

      # Setup SSH
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Add server to known_hosts
      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan barryonweb.com >> ~/.ssh/known_hosts

      # Copy published files to server
      - name: Deploy backend files
        run: |
          scp -r backend/publish/* barry75@barryonweb.com:/var/www/games/backend/

      # Restart backend via systemd
      - name: Restart backend service
        run: |
          ssh barry75@barryonweb.com "sudo systemctl restart games-backend"

      # See logs after restart
      - name: Show backend logs
        run: |
          ssh barry75@barryonweb.com "journalctl -u games-backend -n 50 --no-pager"
